### ISSUE TITLE
change port to 5050 but not working

### ISSUE THREAD

**Issue by tommyMX** [Fahmula/emby-telegram-notifier#14]
Hi,

I put it in the right ip address and changed to port 5050 but not working :-(

<img width="1585" alt="Bildschirmfoto 2024-02-29 um 16 28 05" src="https://github.com/Fahmula/emby-telegram-notifier/assets/36209886/741d0b46-d4ee-4866-8e87-4f3466425095">
<img width="957" alt="Bildschirmfoto 2024-02-29 um 16 27 57" src="https://github.com/Fahmula/emby-telegram-notifier/assets/36209886/8dbb232b-a93b-40c9-bfe3-081d0d386420">

**Comment by Fahmula** [comment]
The port should be 5000
