### ISSUE TITLE
Does not work in emby Version 4.8.4.0

### ISSUE THREAD

**Issue by rmurilloe** [Fahmula/emby-telegram-notifier#16]
Hello, with the new version of emby 4.8.4.0, notifications do not arrive, I hope it can be solved. Thank you so much.

**Comment by Fahmula** [comment]
I just updated to version 4.8.4.0 don't have any issues receiving notifications. What does your docker logs says?

**Comment by DickenSerm** [comment]
Can confirm that.

Docker logs:
`Exception in thread Thread-1 (process_payload):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app.py", line 207, in process_payload
    runtime_sec = runtime_ticks // 10_000_000
                  ~~~~~~~~~~~~~~^^~~~~~~~~~~~
TypeError: unsupported operand type(s) for //: 'str' and 'int'`

**Comment by Fahmula** [comment]
It seems the runtime ticks are not present from emby and it's defaulting to "unknown". Have you tried setting your webhook to trigger on playback start and try playing multiple different movies to see if the issue persists?

**Comment by DickenSerm** [comment]
I'm not trying to play anything. I only receive reports from new media via the webhook.

And unfortunately that no longer works since the update to 4.8.4.0.

Order of my activities:
- I added a new movie
- The telegram message came - Everything was great
- I updated to 4.8.4.0
- I added a new movie
- No telegram message and the above error message appears in the log file

**Comment by DickenSerm** [comment]
I don't know anything about Phython, but if I'm interested in something I'll jump into it :-D

Could it be that the problem is due to the runtime information from the TMDB?

The following line appears in my embylog while adding:

```
Info App: Stopping chapter extraction for <Moviename> because a chapter was found with a position greater than the runtime.
```
Then I noticed that a running time of 120 minutes was listed on themoviedb.org.

However, the film file only lasts 110 minutes.

**Comment by Fahmula** [comment]
I just push an update. Let me know if the issue if fix. Remember to test with a new movie unless you deleted the json database that keeps track of the last 100 titles.

**Comment by rmurilloe** [comment]
Your script works great, the problem seems to be in this movie "Ninja Assassin 2009". It just so happened that I updated Emby and the first movie to post after the update was this one. Thank you very much for sharing your work and dedication.

Spanish -> Su script funciona muy bien, el problema parece estar en esta película "Ninja Assassin 2009".  Se dio la casualidad que actualicé Emby y, la primera película en publicar después de la actualización fue esta. Muchas gracias por compartir su trabajo y dedicación.

**Comment by DickenSerm** [comment]
> I just push an update. Let me know if the issue if fix. Remember to test with a new movie unless you deleted the json database that keeps track of the last 100 titles.

Hey, thanks for taking care of it so quickly. But unfortunately I now get this error message:

```
Exception in thread Thread-1 (process_payload):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app.py", line 208, in process_payload
    hours, remainder = divmod(runtime_sec, 3600)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
```

(Tested with same movie and deleted JSON.)

**Comment by Fahmula** [comment]
It seems the issue stems from missing runtime for that specific movie. I'll update the script to still send notification even if this information is missing. I'll let you know when I do so can test the same movie again.

**Comment by DickenSerm** [comment]
Yes, I had already suspected something like that in the issue above. All right, I've been waiting and will test again. Thanks in advance.

**Comment by Fahmula** [comment]
The issue should be resolved now.

**Comment by DickenSerm** [comment]
Perfect thank you. Now it's working. The film's runtime now says "Unknown" and all other films that I tested afterwards have the correct runtime.

**Comment by rmurilloe** [comment]
Thank you very much for this great script.

Muchas gracias por este estupendo script.
