### ISSUE TITLE
Can't use, sending test message shows error, and log shows : ERROR Key error occurred:'Item'

### ISSUE THREAD

**Issue by Egolas** [Fahmula/emby-telegram-notifier#3]
Thanks for your work. Maybe i missed something to setup properly.

I use your docker to run the app, network set to 'host
', with envs set to:
![image](https://github.com/Fahmula/emby-telegram-notifier/assets/17876505/8e64ac86-60de-402e-8b01-3f45d8975893)

Then, I set emby server webhook like this:
![image](https://github.com/Fahmula/emby-telegram-notifier/assets/17876505/42eb0764-28b3-4522-8ce9-8bf21506e098)

Sending test webhook shows:
![image](https://github.com/Fahmula/emby-telegram-notifier/assets/17876505/54cc44aa-cac3-46cc-8f4f-bb45e4b08274)

And docker log shows:
![image](https://github.com/Fahmula/emby-telegram-notifier/assets/17876505/1ecbb0e6-83bf-453e-b9d8-1906597255a6)

**Comment by Fahmula** [comment]
That's because the test webhook does not send the correct payload. I probably should include it for testing purposes. You can test it be setting the event to playback start and try playing a movie.

**Comment by Fahmula** [comment]
I just added the ability to make use of "Send Test Webhook"
