### ISSUE TITLE
[feature request] add technical info of added video

### ISSUE THREAD

**Issue by Aokromes** [Fahmula/emby-telegram-notifier#5]
how about allow to include quality, languages, subtitles, size and location to message? idk if possible.

**Comment by Fahmula** [comment]
It is possible but why would you need all that extra details? I'm using radarr and sonarr so all that extra info is almost always the same.

**Comment by Aokromes** [comment]
to have it on telegram without need aditional things :)

**Comment by Fahmula** [comment]
These features isn't necessary in my opinion but I could look into making them optional.
