### ISSUE TITLE
Bug publishing movies without trailers

### ISSUE THREAD

**Issue by tonopu** [Fahmula/emby-telegram-notifier#7]
Thank you for this little program that is very useful to me.
However, since the addition of gunicorn, new movies without trailers cannot be published.
Here is the log message:

> IndexError: list index out of range
> Exception in thread Thread-2 (process_payload):
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.11/threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
>   File "/app/app.py", line 195, in process_payload
>     trailer_url = item_details["Items"][0]["RemoteTrailers"][0].get('Url', 'Unknown')
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
> IndexError: list index out of range

No problem for movies with trailers!
If you could look into where this malfunction comes from...
Thank you again for your contribution to Emby.

**Comment by Fahmula** [comment]
It'll look into it and let you know when there is a fix.

**Comment by tonopu** [comment]
thank you ;-)

**Comment by tonopu** [comment]
Many thanks for fixing the problem so quickly.
Everything is fine on my end, whether it's for movies with or without trailers.
And there are still no problems with TV show episodes either.
I wish you all the best in your projects.

**Comment by Fahmula** [comment]
Thanks.
